version: '2.4'

networks:
  nx: 
    driver: bridge

services:
  nx:
    build: ./build
    container_name: nx
    restart: always
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./apps/nx/var:/opt/networkoptix/mediaserver/var
      - ./apps/nx/etc:/opt/networkoptix/mediaserver/etc      
      # - ./config:/config
      # - "./recordings:/etc/hosts/HD Witness Media"
    expose:
      - 7001
    ports:
      - 7001:7001
    networks:
      - nx